import { authenticatedTeamMember, corsHeaders, edgeEnvironment, fail, reply } from '../_shared/googleDriveEdge.ts';

const POLICY_FIELDS = new Set([
  'budget_bytes','reserve_bytes','max_derivative_set_bytes','large_upload_threshold_bytes','info_percent','warning_percent',
  'strong_warning_percent','restrict_large_percent','pause_non_admin_percent','block_percent','migration_retention_days',
  'provisional_retention_hours','draft_retention_hours','migration_batch_size','reconciliation_recheck_hours',
  'emergency_supabase_fallback_enabled','migration_paused',
]);

function cleanBody(value:any){return value&&typeof value==='object'&&!Array.isArray(value)?value:{};}
function safeMigration(row:any){if(!row)return null;return{id:row.id,status:row.status,sourceProvider:row.source_provider,sourceBucket:row.source_bucket,sourceName:String(row.source_path||'').split('/').pop()||'media',destinationProvider:row.destination_provider,sourceRecordType:row.source_record_type,sourceRecordId:row.source_record_id,sourceField:row.source_field,mediaCategory:row.media_category,projectId:row.project_id,creativeMemberId:row.creative_member_id,sourceBytes:Number(row.bytes_total||0),destinationBytes:Number(row.destination_bytes||0),checksumVerified:row.checksum_verified===true,attemptCount:Number(row.attempt_count||0),statusMessage:row.manual_review_reason||row.last_error_message||'',retainSourceUntil:row.retain_source_until,sourceCleanupQueuedAt:row.source_cleanup_queued_at,sourceDeletedAt:row.source_deleted_at,startedAt:row.started_at,verifiedAt:row.verified_at,activatedAt:row.activated_at,completedAt:row.completed_at,updatedAt:row.updated_at};}

Deno.serve(async(request)=>{const env=edgeEnvironment();const cors=corsHeaders(request,env.siteOrigin);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(request.method!=='POST')return fail('METHOD_NOT_ALLOWED','Method not allowed.',405,cors);if(!cors['Access-Control-Allow-Origin'])return fail('ORIGIN_NOT_ALLOWED','This request origin is not allowed.',403,cors);const actor=await authenticatedTeamMember(request,env);if('error'in actor)return fail(actor.error,'Only an active Super Admin can access storage governance.',actor.status,cors);if(actor.role!=='super_admin')return fail('NOT_AUTHORIZED','Only the Super Admin can access storage governance.',403,cors);const body=cleanBody(await request.json().catch(()=>({})));try{
  if(body.action==='dashboard'){const {data,error}=await actor.admin.rpc('get_storage_governance_snapshot');if(error)throw error;return reply({success:true,snapshot:data},200,cors);}
  if(body.action==='update_policy'){const patch=cleanBody(body.policy);if(!Object.keys(patch).length||Object.keys(patch).some((key)=>!POLICY_FIELDS.has(key)))return fail('INVALID_POLICY','The storage policy update contains unsupported fields.',400,cors);const {data,error}=await actor.admin.from('storage_policies').update({...patch,updated_by:actor.user.id,updated_at:new Date().toISOString()}).eq('singleton',true).select('*').single();if(error)return fail('POLICY_UPDATE_FAILED',error.message,400,cors);await actor.admin.from('storage_audit_events').insert({actor_user_id:actor.user.id,action:'storage_policy_updated',target_type:'storage_policy',target_id:'primary',outcome:'completed',details:{changedFields:Object.keys(patch)}});return reply({success:true,policy:data},200,cors);}
  if(body.action==='pause_migration'||body.action==='resume_migration'){const paused=body.action==='pause_migration';const {error}=await actor.admin.from('storage_policies').update({migration_paused:paused,updated_by:actor.user.id,updated_at:new Date().toISOString()}).eq('singleton',true);if(error)throw error;await actor.admin.from('storage_audit_events').insert({actor_user_id:actor.user.id,action:body.action,target_type:'storage_migration',target_id:'global',outcome:'completed',details:{paused}});return reply({success:true,paused},200,cors);}
  if(body.action==='list_migrations'){const status=String(body.status||'');const page=Math.max(0,Number(body.page||0));const size=Math.max(1,Math.min(Number(body.pageSize||25),50));let query=actor.admin.from('storage_migrations').select('*',{count:'exact'}).eq('destination_provider','cloudflare_r2').order('updated_at',{ascending:false}).range(page*size,page*size+size-1);if(status)query=query.eq('status',status);const {data,error,count}=await query;if(error)throw error;return reply({success:true,rows:(data||[]).map(safeMigration),page,pageSize:size,total:count||0},200,cors);}
  if(body.action==='inspect_migration'){const {data,error}=await actor.admin.from('storage_migrations').select('*').eq('id',String(body.id||'')).eq('destination_provider','cloudflare_r2').maybeSingle();if(error)throw error;if(!data)return fail('MIGRATION_NOT_FOUND','The migration record was not found.',404,cors);const {data:objects}=await actor.admin.from('external_media_objects').select('id,provider,media_variant,status,verification_status,accounting_state,trusted_size_bytes,cleanup_status,cleanup_error,last_verified_at,last_reconciled_at').eq('migration_id',data.id).order('media_variant');return reply({success:true,migration:safeMigration(data),objects:objects||[]},200,cors);}
  if(['retry_migration','mark_manual_review','verify_migration'].includes(body.action)){const id=String(body.id||'');const {data:row}=await actor.admin.from('storage_migrations').select('id,status').eq('id',id).eq('destination_provider','cloudflare_r2').maybeSingle();if(!row)return fail('MIGRATION_NOT_FOUND','The migration record was not found.',404,cors);if(body.action==='retry_migration'){if(!['failed','manual_review'].includes(row.status))return fail('MIGRATION_STATE_INVALID','Only failed or manual-review migrations can be retried.',409,cors);await actor.admin.from('storage_migrations').update({status:'queued',manual_review_reason:null,last_error_code:null,last_error_message:null,lock_token:null,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq('id',id).eq('destination_provider','cloudflare_r2');}else if(body.action==='mark_manual_review'){const reason=String(body.reason||'').trim();if(reason.length<8)return fail('REVIEW_REASON_REQUIRED','Provide a clear manual-review reason.',400,cors);await actor.admin.from('storage_migrations').update({status:'manual_review',manual_review_reason:reason,lock_token:null,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq('id',id).eq('destination_provider','cloudflare_r2');}else{const {data:objects}=await actor.admin.from('external_media_objects').select('id').eq('migration_id',id).eq('verification_status','verified');if((objects||[]).length!==3)return fail('MIGRATION_NOT_VERIFIED','All three destination variants must be verified.',409,cors);await actor.admin.from('storage_migrations').update({checksum_verified:true,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('destination_provider','cloudflare_r2');}await actor.admin.from('storage_audit_events').insert({actor_user_id:actor.user.id,action:body.action,target_type:'storage_migration',target_id:id,outcome:'completed',details:{reason:String(body.reason||'').slice(0,500)}});return reply({success:true},200,cors);}
  if(body.action==='authorize_emergency_fallback'){const reason=String(body.reason||'').trim();if(reason.length<8)return fail('FALLBACK_REASON_REQUIRED','Provide a clear emergency reason.',400,cors);const {data:policy}=await actor.admin.from('storage_policies').select('emergency_supabase_fallback_enabled').eq('singleton',true).single();if(!policy?.emergency_supabase_fallback_enabled)return fail('EMERGENCY_FALLBACK_DISABLED','Emergency Supabase fallback is disabled by policy.',409,cors);const {data,error}=await actor.admin.from('storage_emergency_fallback_authorizations').insert({actor_user_id:actor.user.id,reason,target_category:String(body.category||'site_image'),project_id:body.projectId||null,creative_member_id:body.creativeMemberId||null,expires_at:new Date(Date.now()+10*60*1000).toISOString()}).select('id,expires_at').single();if(error)throw error;await actor.admin.from('storage_audit_events').insert({actor_user_id:actor.user.id,action:'emergency_supabase_fallback_authorized',target_type:'fallback_authorization',target_id:data.id,outcome:'allowed',details:{reason,category:String(body.category||'site_image')}});return reply({success:true,authorization:{id:data.id,expiresAt:data.expires_at}},201,cors);}
  return fail('ACTION_NOT_ALLOWED','The requested storage-governance action is unavailable.',400,cors);
}catch(error){return fail(error?.code||'STORAGE_GOVERNANCE_FAILED',String(error?.message||'Storage governance failed.').slice(0,300),500,cors);}});
