import { ArrowDown, ArrowLeft, ArrowUp, Bold, Eye, Heading2, ImagePlus, Italic, Link2, List, ListOrdered, Minus, Quote, Save, Send, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import CreativePostDocument from '../components/CreativePostDocument';
import LoadingState from '../components/LoadingState';
import { applyCreativePostInlineStyle, createCreativePostDraft, createPostBlock, CREATIVE_POST_MAX_IMAGES, loadCreativePostForEdit, normalizeCreativePostDocument, publishCreativePost, removeCreativePostMedia, saveCreativePost, updateCreativePostMedia, uploadCreativePostImage } from '../lib/creativePosts';
import { useAdminAccess } from '../lib/adminAccess';
import { supabase } from '../lib/supabaseClient';
import { useAdminConfirmation } from '../components/admin/AdminDialog';

const blockChoices = [
  ['paragraph', 'Text'], ['heading', 'Heading'], ['quote', 'Quote'], ['bullet_list', 'Bullets'], ['numbered_list', 'Numbers'], ['divider', 'Divider'], ['external_embed', 'Link card'],
];

export default function CreativePostEditor({ create = false }) {
  const { id } = useParams(); const navigate = useNavigate(); const { adminUser } = useAdminAccess();
  const [post, setPost] = useState(null); const [document, setDocument] = useState(null); const [media, setMedia] = useState([]); const [creative, setCreative] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [preview, setPreview] = useState(false); const fileRef = useRef(null);
  const { requestConfirmation, confirmationDialog } = useAdminConfirmation();
  useEffect(() => { let active = true; async function open() { try { const loaded = create ? await createCreativePostDraft() : await loadCreativePostForEdit(id); if (!active) return; setPost(loaded); setDocument(normalizeCreativePostDocument(loaded.document)); setMedia(loaded.creative_post_media || []); if (create) navigate(`/posts/${loaded.id}/edit`, { replace: true }); } catch (reason) { if (active) setError(reason.message); } finally { if (active) setLoading(false); } } open(); return () => { active = false; }; }, [create, id]);
  useEffect(() => { if (!adminUser?.creative_member_id) return; supabase.from('creative_members').select('name,slug').eq('id', adminUser.creative_member_id).single().then(({ data }) => setCreative(data)); }, [adminUser?.creative_member_id]);
  const mediaCount = media.length; const blocks = document?.blocks || [];
  const updateBlock = (index, patch) => setDocument((current) => ({ ...current, blocks: current.blocks.map((block, i) => i === index ? { ...block, ...patch } : block) }));
  const removeBlock = (index) => setDocument((current) => ({ ...current, blocks: current.blocks.filter((_, i) => i !== index) }));
  const moveBlock = (index, delta) => setDocument((current) => { const next = [...current.blocks]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return { ...current, blocks: next }; });
  const addBlock = (type) => setDocument((current) => ({ ...current, blocks: [...current.blocks, createPostBlock(type)] }));
  const previewDocument = useMemo(() => normalizeCreativePostDocument(document), [document]);

  async function save(showNotice = true) { setBusy('saving'); setError(''); try { const saved = await saveCreativePost(post, document); setPost((current) => ({ ...current, ...saved })); if (showNotice) setNotice('Draft saved.'); return saved; } catch (reason) { setError(reason.message); return null; } finally { setBusy(''); } }
  async function publish() { setBusy('publishing'); setError(''); try { const saved = await saveCreativePost(post, document); const published = await publishCreativePost(saved.id); setPost((current) => ({ ...current, ...published })); navigate(`/posts/${published.slug}`); } catch (reason) { setError(reason.message); } finally { setBusy(''); } }
  async function upload(event) { const files = [...(event.target.files || [])]; event.target.value = ''; if (!files.length) return; if (mediaCount + files.length > CREATIVE_POST_MAX_IMAGES) { setError(`A post can contain up to ${CREATIVE_POST_MAX_IMAGES} images.`); return; } setBusy('uploading'); setError(''); try { const added = []; const usedOrders = new Set(media.map((item) => item.display_order)); for (const file of files) { const nextOrder = Array.from({ length: CREATIVE_POST_MAX_IMAGES }, (_, index) => index).find((order) => !usedOrders.has(order)); usedOrders.add(nextOrder); const item = await uploadCreativePostImage(file, { postId: post.id, order: nextOrder, altText: '', onStatus: (status) => setNotice(status?.message || '') }); added.push(item); } setMedia((current) => [...current, ...added]); setDocument((current) => { const existing = current.blocks.findIndex((block) => block.type === 'image_group'); if (existing >= 0) return { ...current, blocks: current.blocks.map((block, i) => i === existing ? { ...block, mediaIds: [...block.mediaIds, ...added.map((item) => item.id)] } : block) }; return { ...current, blocks: [...current.blocks, { ...createPostBlock('image_group'), mediaIds: added.map((item) => item.id) }] }; }); setNotice(`${added.length} image${added.length === 1 ? '' : 's'} added. Add descriptions before publishing.`); } catch (reason) { setError(reason.message); } finally { setBusy(''); } }
  async function removeImage(item) { setBusy('removing'); try { await removeCreativePostMedia(item); setMedia((current) => current.filter((entry) => entry.id !== item.id)); setDocument((current) => ({ ...current, blocks: current.blocks.map((block) => block.type === 'image_group' ? { ...block, mediaIds: block.mediaIds.filter((mediaId) => mediaId !== item.id) } : block).filter((block) => block.type !== 'image_group' || block.mediaIds.length) })); } catch (reason) { setError(reason.message); } finally { setBusy(''); } }
  function confirmImageRemoval(item) { requestConfirmation({ title: 'Remove this image?', description: 'The image will be removed from this draft and queued for safe R2 cleanup.', confirmLabel: 'Remove image', destructive: true, onConfirm: () => removeImage(item) }); }
  async function updateImage(item, patch) { setMedia((current) => current.map((entry) => entry.id === item.id ? { ...entry, ...patch } : entry)); try { await updateCreativePostMedia(item.id, patch); } catch (reason) { setError(reason.message); } }
  function moveImage(itemId, delta) { setDocument((current) => ({ ...current, blocks: current.blocks.map((block) => { if (block.type !== 'image_group') return block; const index = block.mediaIds.indexOf(itemId); const target = index + delta; if (index < 0 || target < 0 || target >= block.mediaIds.length) return block; const mediaIds = [...block.mediaIds]; [mediaIds[index], mediaIds[target]] = [mediaIds[target], mediaIds[index]]; return { ...block, mediaIds }; }) })); }

  if (loading) return <main className="grid min-h-screen place-items-center bg-zinc-950 text-white"><LoadingState label="Preparing your post" /></main>;
  if (error && !post) return <main className="grid min-h-screen place-items-center bg-zinc-950 p-6 text-zinc-200"><p>{error}</p></main>;
  return <main className="min-h-screen bg-zinc-950 text-white">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-zinc-950/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-3 px-4"><Link to={creative?.slug ? `/creatives/${creative.slug}` : '/account'} className="inline-flex min-h-11 items-center gap-2 text-sm text-zinc-300 hover:text-white"><ArrowLeft size={17} /> Profile</Link><div className="flex gap-2"><button type="button" onClick={() => setPreview((value) => !value)} className="creative-editor-button"><Eye size={16} /> <span className="hidden sm:inline">{preview ? 'Edit' : 'Preview'}</span></button><button type="button" onClick={() => save()} disabled={Boolean(busy)} className="creative-editor-button"><Save size={16} /> <span className="hidden sm:inline">Save</span></button><button type="button" onClick={publish} disabled={Boolean(busy)} className="creative-editor-button creative-editor-button--primary"><Send size={16} /> Publish</button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-8 px-4 py-7 lg:grid-cols-[minmax(0,1fr)_20rem]">
      <section className="min-w-0"><div className="mb-6"><p className="text-xs uppercase tracking-[0.18em] text-orange-300">{post.status === 'published' ? 'Published post' : 'Creative draft'}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{preview ? 'Preview' : 'Tell the story your way'}</h1><p className="mt-2 text-sm leading-6 text-zinc-400">Structure the story with text, headings, lists, images, quotes, and links. Lahat Liwa keeps the presentation consistent.</p></div>
        {error && <p role="alert" className="mb-4 rounded-lg border border-red-300/20 bg-red-300/10 p-3 text-sm text-red-100">{error}</p>}{notice && <p role="status" className="mb-4 text-sm text-zinc-400">{notice}</p>}
        {preview ? <div className="rounded-2xl border border-white/10 bg-zinc-900/40 p-5 sm:p-8"><CreativePostDocument document={previewDocument} media={media} /></div> : <div className="grid gap-3">{blocks.map((block, index) => <BlockEditor key={block.id} block={block} index={index} count={blocks.length} onChange={(patch) => updateBlock(index, patch)} onMove={(delta) => moveBlock(index, delta)} onRemove={() => removeBlock(index)} />)}<div className="flex flex-wrap gap-2 rounded-xl border border-dashed border-white/15 p-3">{blockChoices.map(([type, label]) => <button key={type} type="button" onClick={() => addBlock(type)} className="rounded-lg border border-white/10 bg-zinc-900 px-3 py-2 text-sm text-zinc-300 hover:border-orange-300/30 hover:text-white">+ {label}</button>)}</div></div>}
      </section>
      <aside className="min-w-0"><div className="sticky top-24 grid gap-5 rounded-xl border border-white/10 bg-zinc-900/70 p-4"><div><h2 className="font-semibold">Images</h2><p className="mt-1 text-xs leading-5 text-zinc-500">Up to 10 images. Galleries adapt automatically on every screen.</p></div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={upload} className="sr-only" /><button type="button" onClick={() => fileRef.current?.click()} disabled={Boolean(busy) || mediaCount >= CREATIVE_POST_MAX_IMAGES} className="creative-editor-button justify-center"><ImagePlus size={17} /> Add images ({mediaCount}/{CREATIVE_POST_MAX_IMAGES})</button><div className="grid gap-3">{media.map((item, mediaIndex) => <div key={item.id} className="rounded-lg border border-white/10 p-2"><img src={item.thumbnail_url} alt="" className="aspect-video w-full rounded-md object-cover" /><div className="mt-1 flex justify-end"><button type="button" onClick={() => moveImage(item.id, -1)} disabled={mediaIndex === 0} aria-label="Move image earlier" className="block-tool"><ArrowUp size={14} /></button><button type="button" onClick={() => moveImage(item.id, 1)} disabled={mediaIndex === media.length - 1} aria-label="Move image later" className="block-tool"><ArrowDown size={14} /></button></div><input value={item.alt_text || ''} onChange={(event) => setMedia((current) => current.map((entry) => entry.id === item.id ? { ...entry, alt_text: event.target.value } : entry))} onBlur={(event) => updateImage(item, { alt_text: event.target.value, caption: item.caption })} placeholder="Describe the image" className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 px-2 py-2 text-xs text-white placeholder:text-zinc-600" /><input value={item.caption || ''} onChange={(event) => setMedia((current) => current.map((entry) => entry.id === item.id ? { ...entry, caption: event.target.value } : entry))} onBlur={(event) => updateImage(item, { alt_text: item.alt_text, caption: event.target.value })} placeholder="Caption (optional)" className="mt-2 w-full rounded-md border border-white/10 bg-zinc-950 px-2 py-2 text-xs text-white placeholder:text-zinc-600" /><button type="button" onClick={() => confirmImageRemoval(item)} className="mt-2 inline-flex min-h-9 items-center gap-2 text-xs text-red-300"><Trash2 size={14} /> Remove</button></div>)}</div></div></aside>
    </div>{confirmationDialog}
  </main>;
}

function BlockEditor({ block, index, count, onChange, onMove, onRemove }) {
  const textRef = useRef(null);
  const text = block.content?.map((segment) => segment.text).join('') || '';
  const setText = (value) => onChange({ content: [{ text: value, marks: [] }] });
  const styleSelection = (style) => { const field = textRef.current; if (!field || field.selectionStart === field.selectionEnd) return; const start = field.selectionStart; const end = field.selectionEnd; onChange({ content: applyCreativePostInlineStyle(block.content, start, end, style) }); window.setTimeout(() => { field.focus(); field.setSelectionRange(start, end); }, 0); };
  const toggleMark = (mark) => styleSelection({ mark });
  const setLink = () => { const field = textRef.current; if (!field || field.selectionStart === field.selectionEnd) return; const href = window.prompt('Paste an https:// link', 'https://'); if (href !== null) styleSelection({ href }); };
  return <article className="group rounded-xl border border-white/10 bg-zinc-900/60 p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-2"><span className="text-[10px] font-semibold uppercase tracking-[0.16em] text-zinc-500">{block.type.replace('_', ' ')}</span><div className="flex"><button type="button" onClick={() => onMove(-1)} disabled={index === 0} aria-label="Move block up" className="block-tool"><ArrowUp size={15} /></button><button type="button" onClick={() => onMove(1)} disabled={index === count - 1} aria-label="Move block down" className="block-tool"><ArrowDown size={15} /></button><button type="button" onClick={onRemove} aria-label="Remove block" className="block-tool text-red-300"><Trash2 size={15} /></button></div></div>
    {block.content && <><div className="mb-2 flex items-center gap-1"><button type="button" onClick={() => toggleMark('bold')} className="block-tool" title="Bold selected text"><Bold size={15} /></button><button type="button" onClick={() => toggleMark('italic')} className="block-tool" title="Italicize selected text"><Italic size={15} /></button><button type="button" onClick={setLink} className="block-tool" title="Link selected text"><Link2 size={15} /></button><span className="ml-2 text-[10px] text-zinc-600">Select text, then format it</span></div><textarea ref={textRef} rows={block.type === 'heading' ? 2 : 5} value={text} onChange={(event) => setText(event.target.value)} placeholder={block.type === 'heading' ? 'Write a clear heading' : block.type === 'quote' ? 'Add a meaningful quote' : 'Write your story…'} className={`w-full resize-y bg-transparent text-zinc-100 outline-none placeholder:text-zinc-600 ${block.type === 'heading' ? 'text-2xl font-semibold' : block.type === 'quote' ? 'border-l-2 border-orange-300 pl-4 text-lg italic' : 'leading-7'}`} /></>}
    {(block.type === 'bullet_list' || block.type === 'numbered_list') && <textarea rows={5} value={block.items.join('\n')} onChange={(event) => onChange({ items: event.target.value.split('\n') })} placeholder="One item per line" className="w-full resize-y bg-transparent leading-7 text-zinc-100 outline-none placeholder:text-zinc-600" />}
    {block.type === 'divider' && <div className="flex items-center gap-3 text-zinc-600"><Minus /><hr className="flex-1 border-white/15" /></div>}
    {block.type === 'external_embed' && <div className="grid gap-2"><input value={block.label} onChange={(event) => onChange({ label: event.target.value })} placeholder="Link label" className="rounded-md border border-white/10 bg-zinc-950 px-3 py-2 text-sm" /><input value={block.url} onChange={(event) => onChange({ url: event.target.value })} placeholder="https://…" className="rounded-md border border-white/10 bg-zinc-950 px-3 py-2 text-sm" /></div>}
    {block.type === 'image_group' && <p className="text-sm text-zinc-500">This gallery contains {block.mediaIds.length} image{block.mediaIds.length === 1 ? '' : 's'}. Manage image details in the side panel.</p>}
  </article>;
}
