begin;

insert into public.website_studio_entries (entry_key, entry_type, published_data) values
  ('global.navigation', 'global', '{"homeLabel":"Feed","currentWorkLabel":"Work","projectsLabel":"Portfolio","creativesLabel":"Creatives","servicesLabel":"Services","aboutLabel":"About","contactLabel":"Contact","privacyLabel":"Privacy"}'::jsonb),
  ('global.footer', 'global', '{"footerText":"A professional creative network for discovering work, process, stories, projects, and the people behind them."}'::jsonb),
  ('page.home', 'page', '{"heroEyebrow":"Lahat Liwa creative network","heroTitle":"Discover what Creatives are making now.","heroDescription":"Follow published work, photography, design, writing, project updates, and creative process from people across the Lahat Liwa network."}'::jsonb),
  ('page.about', 'page', '{"eyebrow":"About Lahat Liwa","title":"A professional home for creative work and the people behind it.","intro":"Lahat Liwa is a professional creative social portfolio where Creatives publish their work, process, writing, photography, and projects—and where viewers can discover the people behind that work.","purposeEyebrow":"Purpose","purposeTitle":"Why the network exists","journey":"Creative work deserves more than a static gallery. Lahat Liwa gives each Creative a professional profile and living wall where finished work, experiments, process, and formal projects can be shared with context.","findEyebrow":"Inside the platform","findTitle":"One connected creative network","workTitle":"Creative feed","workDescription":"Follow newly published posts, photography, writing, process, and professional work from Creatives across the network.","portfolioTitle":"Formal projects","portfolioDescription":"Explore completed case studies and current projects with clear outcomes, progress, and contributor credit.","creativesTitle":"Creative profiles","creativesDescription":"Open a Creative wall to see their identity, disciplines, links, posts, and formal project contributions.","inquiriesTitle":"Professional inquiries","inquiriesDescription":"Ask about a specific work or describe a new project, collaboration, event, or opportunity in your own words.","collaborationEyebrow":"Professional connection","collaborationTitle":"Discovery that can lead to meaningful work","collaborationDescription":"The platform connects creative identity and published work with clear paths for clients and collaborators to start a professional conversation.","collaborationNote":"A profile documents creative identity and published work. Availability, scope, schedule, and working arrangements are confirmed separately.","directionEyebrow":"Direction","directionTitle":"Rooted in Aklan, open to creative work and connections everywhere.","directionDescription":"Lahat Liwa is built from Aklan as a modern professional canvas for Creatives, clients, communities, and collaborators."}'::jsonb),
  ('page.creatives', 'page', '{"directoryEyebrow":"Creative network","directoryTitle":"Discover the people behind the work.","directoryDescription":"Explore professional profiles, published posts, disciplines, external links, and formal project contributions across Lahat Liwa."}'::jsonb),
  ('page.explore', 'page', '{"eyebrow":"Work in progress","title":"Follow formal projects while they are taking shape.","description":"See active client work, event coverage, production milestones, and public progress. Finished projects move into the permanent portfolio."}'::jsonb),
  ('page.projects', 'page', '{"eyebrow":"Formal portfolio","title":"Projects preserved with context.","description":"Explore completed case studies, outcomes, media, progress, and clearly credited Creative contributions."}'::jsonb),
  ('page.services', 'page', '{"title":"Start with what you want to make possible.","intro":"Tell us about the goal, audience, problem, event, idea, or opportunity. You do not need to choose from a fixed service category."}'::jsonb)
on conflict (entry_key) do update
set published_data = public.website_studio_entries.published_data || excluded.published_data,
    draft_data = case when public.website_studio_entries.draft_data is null then null else public.website_studio_entries.draft_data || excluded.published_data end,
    published_version = public.website_studio_entries.published_version + 1,
    published_at = now(),
    updated_at = now();

commit;
