import { Copy, ExternalLink, Eye, ImagePlus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Navigate, useNavigate, useParams } from 'react-router-dom';
import AdminLayout from '../../components/admin/AdminLayout';
import { AdminButton, AdminEmptyState, AdminNotice, AdminPageHeader, ResponsiveFormSection, StickyMobileActions } from '../../components/admin/AdminUI';
import LoadingState from '../../components/LoadingState';
import { isPrivilegedRole, useAdminAccess } from '../../lib/adminAccess';
import { copyText } from '../../lib/clipboard';
import { uploadSiteAsset } from '../../lib/contentApi';
import { parseList, slugify } from '../../lib/helpers';
import { uploadStatusText } from '../../lib/imageCompression';
import { socialLinksFromText } from '../../lib/socialLinks';
import { supabase } from '../../lib/supabaseClient';
import UnsavedChangesGuard from '../../components/admin/UnsavedChangesGuard';

const emptyCreative = { name:'', slug:'', role:'', short_bio:'', full_bio:'', profile_image_url:'', cover_image:'', skills:'', social_links:'', availability_status:'', is_featured:false, is_published:true, display_order:'' };
const lineInput = 'w-full border-0 border-b border-white/[0.12] bg-transparent px-0 py-2.5 text-white outline-none transition placeholder:text-zinc-700 focus:border-amber-200/60';

function Field({ label, value, onChange, type='text', required=false, onBlur }) { return <label className="grid gap-1.5 text-sm text-zinc-400"><span>{label}</span><input className={lineInput} type={type} required={required} value={value} onChange={(e)=>onChange(e.target.value)} onBlur={onBlur} /></label>; }
function TextArea({ label, value, onChange, rows=4, hint }) { return <label className="grid gap-1.5 text-sm text-zinc-400"><span>{label}</span><textarea className={`${lineInput} resize-y leading-6`} rows={rows} value={value} onChange={(e)=>onChange(e.target.value)} />{hint && <span className="text-xs text-zinc-600">{hint}</span>}</label>; }
function Section({ title, description, children }) { return <ResponsiveFormSection title={title} description={description}>{children}</ResponsiveFormSection>; }

export default function CreativeEditor() {
  const { role } = useAdminAccess(); const { id } = useParams(); const navigate = useNavigate();
  const editing = Boolean(id); const [form,setForm]=useState(emptyCreative); const [loading,setLoading]=useState(editing); const [saving,setSaving]=useState(false); const [dirty,setDirty]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const update=(key,value)=>{setDirty(true);setForm((current)=>({...current,[key]:value,slug:key==='name'&&!editing?slugify(value):current.slug}));};

  useEffect(()=>{ window.scrollTo({top:0,behavior:'auto'}); if(!editing)return; supabase.from('creative_members').select('*').eq('id',id).maybeSingle().then(({data,error:loadError})=>{ if(loadError)setError(loadError.message); if(data)setForm({...emptyCreative,...data,skills:(data.skills||[]).join(', '),social_links:(data.social_links||[]).map((item)=>`${item.label}: ${item.href}`).join('\n'),display_order:data.display_order??''}); setDirty(false); setLoading(false); }); },[id,editing]);

  async function upload(file,kind){ if(!file)return; setSaving(true);setError('');let optimized='';try{const cover=kind==='cover';const url=await uploadSiteAsset(file,cover?'creatives/covers':'creatives',cover?'creativeCover':'creativeProfile',{onStatus(status){setNotice(uploadStatusText(status));if(status?.message)optimized=status.message;}});update(cover?'cover_image':'profile_image_url',url);setNotice(optimized||`${cover?'Cover':'Profile'} photo ready to save.`);}catch(uploadError){setError(uploadError.message||'Upload failed.');}finally{setSaving(false);} }
  async function save(event){event.preventDefault();setSaving(true);setError('');setNotice('');const payload={name:form.name.trim(),slug:slugify(form.slug||form.name),role:form.role.trim(),short_bio:form.short_bio?.trim()||null,full_bio:form.full_bio?.trim()||null,profile_image_url:form.profile_image_url||null,cover_image:form.cover_image||null,skills:parseList(form.skills),social_links:socialLinksFromText(form.social_links||''),availability_status:form.availability_status?.trim()||null,is_featured:form.is_featured,is_published:form.is_published,display_order:form.display_order===''?null:Number(form.display_order),updated_at:new Date().toISOString()};const query=editing?supabase.from('creative_members').update(payload).eq('id',id).select('*').single():supabase.from('creative_members').insert(payload).select('*').single();const{data,error:saveError}=await query;if(saveError)setError(saveError.message);else{setDirty(false);setNotice(editing?'Creative profile saved.':'Creative profile created.');if(!editing)navigate(`/admin/creatives/${data.id}/edit`,{replace:true});}setSaving(false);}
  async function copyLink(){try{await copyText(`${window.location.origin}/creatives/${form.slug}`);setNotice('Profile link copied.');}catch(copyError){setError(copyError.message||'Could not copy link.');}}

  if(!isPrivilegedRole(role))return <Navigate to={role==='creative'||role==='editor'?'/admin/my-profile':'/admin/dashboard'} replace/>;
  if(loading)return <AdminLayout><LoadingState label="Loading creative editor"/></AdminLayout>;
  if(editing&&!form.id)return <AdminLayout><AdminEmptyState title="Creative profile not found" action={<AdminButton to="/admin/creatives">Back to creatives</AdminButton>}/></AdminLayout>;
  return <AdminLayout><UnsavedChangesGuard dirty={dirty&&!saving}/><AdminPageHeader eyebrow="Creative profile" title={editing?'Edit Creative':'Add Creative'} description="Manage profile content, media, links, and visibility." action={<AdminButton to="/admin/creatives" variant="ghost">Back to Creatives</AdminButton>}/>{error&&<AdminNotice className="mb-5">{error}</AdminNotice>}{notice&&<AdminNotice tone="success" className="mb-5">{notice}</AdminNotice>}
    <form onSubmit={save} className="mx-auto max-w-5xl">
      <Section title="Basic Information"><div className="grid gap-6 md:grid-cols-2"><Field label="Name / display name" required value={form.name} onChange={(v)=>update('name',v)}/><Field label="Slug" required value={form.slug} onChange={(v)=>update('slug',v)} onBlur={()=>update('slug',slugify(form.slug))}/><Field label="Role / title" required value={form.role} onChange={(v)=>update('role',v)}/><Field label="Availability" value={form.availability_status||''} onChange={(v)=>update('availability_status',v)}/></div></Section>
      <Section title="Profile Content"><div className="grid gap-6"><TextArea label="Short bio" rows={3} value={form.short_bio||''} onChange={(v)=>update('short_bio',v)}/><TextArea label="Full bio" rows={6} value={form.full_bio||''} onChange={(v)=>update('full_bio',v)}/><Field label="Skills, comma-separated" value={form.skills||''} onChange={(v)=>update('skills',v)}/></div></Section>
      <Section title="Profile Media" description="Uploads retain the existing compression and optimization rules."><div className="grid gap-7 md:grid-cols-2"><div className="grid content-start gap-3"><p className="text-sm text-zinc-400">Profile photo</p>{form.profile_image_url?<img src={form.profile_image_url} alt="Profile preview" className="h-28 w-28 rounded-full object-cover"/>:<div className="grid h-28 w-28 place-items-center rounded-full bg-white/[0.04] text-2xl text-zinc-600">{form.name?.slice(0,1)||'L'}</div>}<div className="flex flex-wrap gap-2"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-white/[0.12] bg-white/[0.035] px-3 text-sm text-zinc-300 transition hover:border-amber-200/35 hover:bg-white/[0.07] hover:text-white"><ImagePlus size={15}/>{form.profile_image_url?'Replace':'Upload'}<input className="sr-only" type="file" accept="image/*" onChange={(e)=>upload(e.target.files?.[0],'profile')}/></label>{form.profile_image_url&&<AdminButton variant="ghost" onClick={()=>update('profile_image_url','')}><Trash2 size={15}/> Remove</AdminButton>}</div></div><div className="grid content-start gap-3"><p className="text-sm text-zinc-400">Cover photo</p>{form.cover_image?<img src={form.cover_image} alt="Cover preview" className="aspect-[16/6] w-full object-cover"/>:<div className="grid aspect-[16/6] w-full place-items-center bg-white/[0.025] text-sm text-zinc-600">No cover photo</div>}<div className="flex flex-wrap gap-2"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-white/[0.12] bg-white/[0.035] px-3 text-sm text-zinc-300 transition hover:border-amber-200/35 hover:bg-white/[0.07] hover:text-white"><ImagePlus size={15}/>{form.cover_image?'Replace':'Upload'}<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e.target.files?.[0],'cover')}/></label>{form.cover_image&&<AdminButton variant="ghost" onClick={()=>update('cover_image','')}><Trash2 size={15}/> Remove</AdminButton>}</div></div></div></Section>
      <Section title="Social Links"><TextArea label="Links" rows={5} value={form.social_links||''} onChange={(v)=>update('social_links',v)} hint="One per line as Label: URL. Existing platform detection remains active."/></Section>
      <Section title="Visibility"><div className="grid gap-6 md:grid-cols-3"><label className="flex items-center gap-3 border-b border-white/[0.1] py-3 text-sm text-zinc-300"><input type="checkbox" checked={form.is_published} onChange={(e)=>update('is_published',e.target.checked)} className="h-4 w-4 accent-amber-300"/> Published</label><label className="flex items-center gap-3 border-b border-white/[0.1] py-3 text-sm text-zinc-300"><input type="checkbox" checked={form.is_featured} onChange={(e)=>update('is_featured',e.target.checked)} className="h-4 w-4 accent-amber-300"/> Featured</label><Field label="Display order" type="number" value={form.display_order??''} onChange={(v)=>update('display_order',v)}/></div></Section>
      <StickyMobileActions><AdminButton type="submit" variant="primary" disabled={saving}><Save size={16}/>{saving?'Saving...':editing?'Save Changes':'Create Creative'}</AdminButton><AdminButton to="/admin/creatives" variant="ghost">Cancel</AdminButton>{editing&&<><AdminButton to={`/admin/creatives?preview=${id}`}><Eye size={15}/> Preview</AdminButton><AdminButton onClick={copyLink}><Copy size={15}/> Copy link</AdminButton>{form.is_published&&<AdminButton to={`/creatives/${form.slug}`}><ExternalLink size={15}/> Open Public</AdminButton>}</>}</StickyMobileActions>
    </form></AdminLayout>;
}
