import { ExternalLink, Save, Trash2, Upload } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Navigate, useNavigate, useParams } from 'react-router-dom';
import AdminLayout from '../../components/admin/AdminLayout';
import { AdminButton, AdminEmptyState, AdminNotice, AdminPageHeader, ResponsiveFormSection, StickyMobileActions } from '../../components/admin/AdminUI';
import ServiceTaxonomyPreview from '../../components/admin/ServiceTaxonomyPreview';
import LoadingState from '../../components/LoadingState';
import { isPrivilegedRole, useAdminAccess } from '../../lib/adminAccess';
import { resolvePublicAssetUrl, uploadSiteAsset } from '../../lib/contentApi';
import { parseList, slugify } from '../../lib/helpers';
import { uploadStatusText } from '../../lib/imageCompression';
import { branchKeyFromRecord } from '../../lib/serviceRequest';
import { supabase } from '../../lib/supabaseClient';

const emptyBranch={name:'',slug:'',description:'',included_services:'',icon_url:'',cta_label:'Submit request',cta_url:'/inquiry',display_order:'',is_published:true};
const lineInput='w-full border-0 border-b border-white/[0.12] bg-transparent px-0 py-2.5 text-white outline-none transition placeholder:text-zinc-700 focus:border-amber-200/60';
function Field({label,value,onChange,type='text',required=false,onBlur}){return <label className="grid gap-1.5 text-sm text-zinc-400"><span>{label}</span><input className={lineInput} type={type} required={required} value={value} onChange={(e)=>onChange(e.target.value)} onBlur={onBlur}/></label>;}
function TextArea({label,value,onChange,rows=5,hint}){return <label className="grid gap-1.5 text-sm text-zinc-400"><span>{label}</span><textarea className={`${lineInput} resize-y leading-6`} rows={rows} value={value} onChange={(e)=>onChange(e.target.value)}/>{hint&&<span className="text-xs text-zinc-600">{hint}</span>}</label>;}
function Section({title,description,children}){return <ResponsiveFormSection title={title} description={description}>{children}</ResponsiveFormSection>;}

export default function ServiceBranchEditor(){
  const{role}=useAdminAccess();const{id}=useParams();const navigate=useNavigate();const editing=Boolean(id);
  const[form,setForm]=useState(emptyBranch);const[loading,setLoading]=useState(editing);const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const update=(key,value)=>setForm((current)=>({...current,[key]:value,slug:key==='name'&&!editing?slugify(value):current.slug}));
  useEffect(()=>{window.scrollTo({top:0,behavior:'auto'});if(!editing)return;supabase.from('service_branches').select('*').eq('id',id).maybeSingle().then(({data,error:loadError})=>{if(loadError)setError(loadError.message);if(data)setForm({...emptyBranch,...data,included_services:Array.isArray(data.included_services)?data.included_services.join(', '):'',display_order:data.display_order??''});setLoading(false);});},[editing,id]);
  async function uploadIcon(file){if(!file)return;setUploading(true);setError('');let optimized='';try{const url=await uploadSiteAsset(file,'service-branches','serviceMedia',{onStatus(status){setNotice(uploadStatusText(status));if(status?.message)optimized=status.message;}});update('icon_url',url);setNotice(optimized||'Service icon ready to save.');}catch(uploadError){setError(uploadError.message||'Service icon upload failed.');}finally{setUploading(false);}}
  async function save(event){event.preventDefault();setSaving(true);setError('');setNotice('');const payload={name:form.name.trim(),slug:slugify(form.slug||form.name),description:form.description?.trim()||null,included_services:parseList(form.included_services),icon_url:form.icon_url||null,cta_label:form.cta_label?.trim()||null,cta_url:form.cta_url?.trim()||null,display_order:form.display_order===''?null:Number(form.display_order),is_published:form.is_published,updated_at:new Date().toISOString()};const query=editing?supabase.from('service_branches').update(payload).eq('id',id).select('*').single():supabase.from('service_branches').insert(payload).select('*').single();const{data,error:saveError}=await query;if(saveError)setError(saveError.message);else{setNotice(editing?'Service branch saved.':'Service branch created.');if(!editing)navigate(`/admin/service-branches/${data.id}/edit`,{replace:true});}setSaving(false);}
  if(!isPrivilegedRole(role))return <Navigate to="/admin/dashboard" replace/>;
  if(loading)return <AdminLayout><LoadingState label="Loading service branch editor"/></AdminLayout>;
  if(editing&&!form.id)return <AdminLayout><AdminEmptyState title="Service branch not found" action={<AdminButton to="/admin/service-branches">Back to Service Branches</AdminButton>}/></AdminLayout>;
  const branchKey=branchKeyFromRecord(form);
  return <AdminLayout><AdminPageHeader eyebrow="Collective services" title={editing?'Edit Service Branch':'Add Service Branch'} description="Manage branch content, media, visibility, and ordering." action={<AdminButton to="/admin/service-branches" variant="ghost">Back to Service Branches</AdminButton>}/>{error&&<AdminNotice className="mb-5">{error}</AdminNotice>}{notice&&<AdminNotice tone="success" className="mb-5">{notice}</AdminNotice>}
    <form onSubmit={save} className="mx-auto max-w-5xl">
      <Section title="Branch Identity"><div className="grid gap-6 md:grid-cols-2"><Field label="Branch name" required value={form.name} onChange={(v)=>update('name',v)}/><Field label="Slug" required value={form.slug} onChange={(v)=>update('slug',v)} onBlur={()=>update('slug',slugify(form.slug))}/><Field label="CTA label" value={form.cta_label||''} onChange={(v)=>update('cta_label',v)}/><Field label="CTA URL" value={form.cta_url||''} onChange={(v)=>update('cta_url',v)}/></div></Section>
      <Section title="Branch Content" description="Public service choices use the shared six-category taxonomy; detailed needs remain available in the inquiry follow-up questions."><TextArea label="Description" rows={6} value={form.description||''} onChange={(v)=>update('description',v)} hint="Describe flexible support without promising a fixed package, location, schedule, or acceptance."/>{branchKey?<ServiceTaxonomyPreview branchKey={branchKey}/>:<Field label="Legacy service categories" value={form.included_services||''} onChange={(v)=>update('included_services',v)}/>}</Section>
      <Section title="Media" description="Raster images are resized to 600px and optimized to 300 KB; SVG keeps its existing limit."><div className="grid gap-4 sm:grid-cols-[8rem_1fr] sm:items-center"><div className="grid h-28 w-28 place-items-center bg-white/[0.025]">{form.icon_url?<img src={resolvePublicAssetUrl(form.icon_url)} alt="Icon preview" className="max-h-20 max-w-20 object-contain"/>:<span className="text-sm text-zinc-600">No icon</span>}</div><div className="flex flex-wrap gap-2"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-md border border-white/[0.12] bg-white/[0.035] px-3 text-sm text-zinc-300 transition hover:border-amber-200/35 hover:bg-white/[0.07] hover:text-white"><Upload size={15}/>{uploading?'Optimizing...':form.icon_url?'Replace icon':'Upload icon'}<input className="sr-only" type="file" accept="image/*" disabled={uploading||saving} onChange={(e)=>{uploadIcon(e.target.files?.[0]);e.target.value='';}}/></label>{form.icon_url&&<AdminButton variant="ghost" onClick={()=>update('icon_url','')}><Trash2 size={15}/> Remove</AdminButton>}</div></div></Section>
      <Section title="Visibility and Ordering"><div className="grid gap-6 md:grid-cols-2"><label className="flex items-center gap-3 border-b border-white/[0.1] py-3 text-sm text-zinc-300"><input type="checkbox" checked={form.is_published} onChange={(e)=>update('is_published',e.target.checked)} className="h-4 w-4 accent-amber-300"/> Published</label><Field label="Display order" type="number" value={form.display_order??''} onChange={(v)=>update('display_order',v)}/></div></Section>
      <StickyMobileActions><AdminButton type="submit" variant="primary" disabled={saving||uploading}><Save size={16}/>{saving?'Saving...':editing?'Save Changes':'Create Branch'}</AdminButton><AdminButton to="/admin/service-branches" variant="ghost">Cancel</AdminButton><AdminButton to="/services"><ExternalLink size={15}/> Open Public Services</AdminButton></StickyMobileActions>
    </form></AdminLayout>;
}
